# arguments for dataset
dataset: coco
nclass: 81
crop_size: 513
data_root: /home/y212202015/test/data/COCO2017

# arguments for training
epochs: 30
batch_size: 2 # per GPU x 4 GPUs
lr: 0.004
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

feat_ali_weight: 0.1

warm_up: 0

F-Drop: True

F-Noise: True


unsupervised_w: 0.01
ramp_up: 0.1 

# arguments for model
backbone: xception
dilations: [6, 12, 18]
